In [1]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.9844, 0.5834, 0.5408],
        [0.7734, 0.8265, 0.0402],
        [0.5957, 0.6189, 0.9299],
        [0.0072, 0.7148, 0.4223],
        [0.6532, 0.5504, 0.2713]])


In [2]:
import torch
print(torch.__version__)       # PyTorch version
print(torch.version.cuda)      # CUDA version PyTorch was built with
print(torch.cuda.is_available())  # Should be True if GPU is working


2.8.0+cu128
12.8
True


In [3]:
import torch, torchaudio
print(torch.__version__)           # should be 2.8.0+cu128
print(torchaudio.__version__)      # should be 2.8.0+cu128
print(torch.cuda.is_available())   # True


2.8.0+cu128
2.8.0+cu128
True


In [6]:
import numpy as np

# Example: 2 samples, 4 bins
logits = np.array([[1.2, 0.5, -0.3, 2.0],
                   [0.1, 1.5, 0.7, -0.8]])  # shape (2, 4)

# Softmax over last dimension
probs = np.exp(logits) / np.exp(logits).sum(axis=-1, keepdims=True)
probs

# Example bin centers
bins = np.array([1.0, 2.0, 3.0, 4.0])  # shape (4,)

# Expected value per sample
# expected = (probs * bins).sum(axis=-1)
expected = (probs * bins).sum(axis=-1)

print("Logits:\n", logits)
print("Probabilities:\n", probs)
print("Expected MOS:\n", expected)

Logits:
 [[ 1.2  0.5 -0.3  2. ]
 [ 0.1  1.5  0.7 -0.8]]
Probabilities:
 [[0.25346895 0.12586896 0.05655657 0.56410552]
 [0.13728931 0.5567356  0.25015743 0.05581767]]
Expected MOS:
 [2.93129867 2.22450346]
